name: Test
on: [ push, pull_request, workflow_dispatch ]
jobs:
  test:
    strategy:
      matrix:
        node: [ 12, 14, 16 ]
    name: Test on Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm i
      - run: npm test
